_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 7
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": linux-x86_64
agent:
    value: basic
batch_size:
    value: 8
class_names:
    value: ship
dataset:
    value: voc_detection
epochs:
    value: 10
lr:
    value: 0.001
metric:
    value: voc_ap
model:
    value: faster_rcnn
num_classes:
    value: 2
root:
    value: /home/mark/sfda/Official-SSDD-OPEN/BBox_SSDD/voc_style
split:
    value: train
wandb_project:
    value: sfda-voc-test
wandb_run_name:
    value: voc-basic-agent-test
