"""Add reproducibility column to runs

Revision ID: 9de5acc813c1
Revises: 
Create Date: 2026-01-24 02:24:46.506222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de5acc813c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_versions_category'), 'component_versions', ['category'], unique=False)
    op.create_index(op.f('ix_component_versions_hash'), 'component_versions', ['hash'], unique=True)
    op.create_index(op.f('ix_component_versions_id'), 'component_versions', ['id'], unique=False)
    op.create_index(op.f('ix_component_versions_name'), 'component_versions', ['name'], unique=False)
    op.create_index(op.f('ix_component_versions_path'), 'component_versions', ['path'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('gpu_util', sa.Float(), nullable=True),
    sa.Column('vram_used', sa.Integer(), nullable=True),
    sa.Column('vram_total', sa.Integer(), nullable=True),
    sa.Column('gpu_temperature', sa.Float(), nullable=True),
    sa.Column('gpu_power_usage', sa.Float(), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=True),
    sa.Column('gpus_detail', sa.JSON(), nullable=True),
    sa.Column('cpu_util', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('disk_free', sa.Float(), nullable=True),
    sa.Column('torch_version', sa.String(), nullable=True),
    sa.Column('cuda_version', sa.String(), nullable=True),
    sa.Column('code_version', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('active_jobs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_host_id'), 'devices', ['host_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('experiment_component_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_uid', sa.String(), nullable=True),
    sa.Column('component_path', sa.String(), nullable=True),
    sa.Column('component_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_component_manifests_experiment_uid'), 'experiment_component_manifests', ['experiment_uid'], unique=False)
    op.create_index(op.f('ix_experiment_component_manifests_id'), 'experiment_component_manifests', ['id'], unique=False)
    op.create_table('queue_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('config_path', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('error_log_path', sa.String(), nullable=True),
    sa.Column('assigned_device', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('log_hash', sa.String(), nullable=True),
    sa.Column('error_log_hash', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('server_origin', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('remote_mtime', sa.Integer(), nullable=True),
    sa.Column('recovery_checkpoint', sa.JSON(), nullable=True),
    sa.Column('last_indexed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_experiments_experiment_uid'), 'queue_experiments', ['experiment_uid'], unique=True)
    op.create_index(op.f('ix_queue_experiments_id'), 'queue_experiments', ['id'], unique=False)
    op.create_index(op.f('ix_queue_experiments_project'), 'queue_experiments', ['project'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('run_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('config_path', sa.String(), nullable=True),
    sa.Column('metrics_path', sa.String(), nullable=True),
    sa.Column('checkpoint_path', sa.String(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('final_metrics', sa.JSON(), nullable=True),
    sa.Column('max_metrics', sa.JSON(), nullable=True),
    sa.Column('min_metrics', sa.JSON(), nullable=True),
    sa.Column('mean_metrics', sa.JSON(), nullable=True),
    sa.Column('median_metrics', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('file_fingerprint', sa.String(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('reproducibility', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project', 'run_name', name='uix_project_run_name')
    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_project'), 'runs', ['project'], unique=False)
    op.create_index(op.f('ix_runs_run_name'), 'runs', ['run_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_run_name'), table_name='runs')
    op.drop_index(op.f('ix_runs_project'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_queue_experiments_project'), table_name='queue_experiments')
    op.drop_index(op.f('ix_queue_experiments_id'), table_name='queue_experiments')
    op.drop_index(op.f('ix_queue_experiments_experiment_uid'), table_name='queue_experiments')
    op.drop_table('queue_experiments')
    op.drop_index(op.f('ix_experiment_component_manifests_id'), table_name='experiment_component_manifests')
    op.drop_index(op.f('ix_experiment_component_manifests_experiment_uid'), table_name='experiment_component_manifests')
    op.drop_table('experiment_component_manifests')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_host_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_component_versions_path'), table_name='component_versions')
    op.drop_index(op.f('ix_component_versions_name'), table_name='component_versions')
    op.drop_index(op.f('ix_component_versions_id'), table_name='component_versions')
    op.drop_index(op.f('ix_component_versions_hash'), table_name='component_versions')
    op.drop_index(op.f('ix_component_versions_category'), table_name='component_versions')
    op.drop_table('component_versions')
    # ### end Alembic commands ###
