# config/irg_sfda.yaml

agent: main

model:
  detector: faster_rcnn_fpn

loss: 
optimizer: sgd
scheduler: cosine

metric: detmap          # ← renamed from 'metrics' to 'metric'
checkpoint: save_best
logger: wandb

dataloader:
  target: foggy_cityscapes

lr: 0.01
weight_decay: 1e-4
momentum: 0.9
epochs: 5
batch_size: 4
workers: 4
source_ckpt: weights/faster_rcnn_coco.pth