agent: basic
dataset: voc_detection
root: /home/mark/sfda/Official-SSDD-OPEN/BBox_SSDD/voc_style
split: train
class_names:
  - ship

model: faster_rcnn
num_classes: 2

epochs: 10
batch_size: 8
lr: 0.001

metric: voc_ap

# wandb
wandb_project: sfda-voc-test
wandb_run_name: voc-basic-agent-test