# config/ssl/fixmatch.yaml
# Configuration for the standard FixMatch agent.
# === General Configuration ===
run_name: run_{{date}}_{{num_labeled}}
description: Standard FixMatch Configuration
author: Hyunseo Choung
date: "2025-09-01"

agent: fixmatch
device: 0

# === Global Hyperparameters ===
epochs: 256
batch_size: 16
num_workers: 4
data_root: "./data/mstar"
size: 128
num_classes: 10
pretrained: false
padding: 16
padding_mode: reflect
# Normalization parameters for MSTAR dataset
mean: !!python/tuple [0.1414, 0.1414, 0.1414]
std: !!python/tuple [0.1258, 0.1258, 0.1258]
lr: 0.003
weight_decay: 0
log_dir: "./logs/fixmatch"

# === Grid Search & Agent-specific Hyperparameters ===
steps_per_epoch: 128
num_labeled: 100

mu: 7
lambda_fixmatch: 1.0
confidence_threshold: 0.95

# === Component Selections ===

model: resnet18

optimizer: adam

# For FixMatch, the dataset needs to return two augmented views of each image.
# We use a special transform component for this.
dataset:
  train: mstar(split="train")
  val: mstar(split="test")
dataloader:
  labeled: basic
  unlabeled: basic
  val: basic
sampler:
  labeled: subset_random
  unlabeled: subset_random
transform:
  weak: "resize | random_flip | random_crop | to_tensor | normalize"
  strong: "resize | random_flip | random_crop | adaptive_rand_augment(magnitude_min=0, magnitude_max=30) | to_tensor | normalize"
  val: "resize | to_tensor | normalize"
loss:
  supervised: cross_entropy(reduction="mean")
  unsupervised: cross_entropy(reduction="none")
metric:
  val: accuracy
logger: csv
