# config/ssl/fixmatch.yaml
# Configuration for the standard FixMatch agent.
# === General Configuration ===
run_name: run_{{date}}_{{num_labeled}}_fixmatch
description: Standard FixMatch Configuration
author: Hyunseo Choung
date: "2025-08-22"

agent: fixmatch

# === Global Hyperparameters ===
epochs: 20
batch_size: 16
num_workers: 4
data_root: "./data/mstar"
num_classes: 10
pretrained: true
lr: 0.002
weight_decay: 0.0005
log_dir: "./logs/fixmatch"

# === Grid Search & Agent-specific Hyperparameters ===
steps_per_epoch: 1024
num_labeled:
  - 50
  - 100
  - 200

mu: 7
lambda_fixmatch: 1.0
confidence_threshold: 0.95

# === Component Selections ===

model: resnet18

optimizer: adam

# For FixMatch, the dataset needs to return two augmented views of each image.
# We use a special transform component for this.
dataset:
  train: mstar(split="TRAIN", transform=fixmatch_transform)
  val: mstar(split="TEST", transform=weak)

dataloader:
  labeled: basic(shuffle=True)
  unlabeled: basic(shuffle=True)
  val: basic(shuffle=False)

sampler:
  labeled: subset_random
  unlabeled: subset_random

# Define the weak and strong augmentations that fixmatch_transform will use.
transform:
  weak: "resize(size=128) | random_flip | to_tensor | normalize"
  strong: "resize(size=128) | random_flip | rand_augment | to_tensor | normalize"

loss:
  supervised: cross_entropy
  unsupervised: cross_entropy

metric:
  val: accuracy

logger: csv
